--- 
title: "Cross Lagged Regression"
author: "Christopher Weber"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  Cross Lagged Regression
link-citations: true
github-repo: crweber9874/advancedRegression
---


# Preface {-}

The Cross-Lagged Panel Model (CLPM) is widely accepted as a standard method for longitudinal causal analysis in political science. Its application, however, is often susceptible to unaccounted time-invariant confounders and measurement error, leading to spurious estimates of autoregressive and cross-lagged relationships, as well as bias in statistical inferences and substantive conclusions. In these documentation files, I demonstrate the similarities and differences between different panel analysis models, showing in particular, that the standard CLPM is strongly related to a more flexible and robust alternatives, the change score regression model and the random-intercept cross-lagged regression model. Both the Latent Change Model (LCM) and the Random Intercept Cross-Lagged Panel Model (RI-CLPM) extend the standard CLPM by explicitly modeling "unit level" effects. In simulations and empirical examples, we show the myriad paths by which the CLPM produces biased parameter estimates due to unmodeled, stable-unit effects. Both approaches allow for "constant" differences between units over time: In the RI-CLPM, this is represented by a factor corresponding to unit-mean variation in the observed variables, a "random-intercept" while in the LCM, this is captured through a factor corresponding to unit-level change over time, a "random slope."

This documentation elaborates upon:

* The theoretical background for the CLPM, RI-CLPM, and LCM, highlighting their similarities and differences.
* An introduction to the `crossLagR` package, which includes various utilities to estimate and simulate effects from these models.
* A Monte Carlo simulation procedure that examines the degree of bias in parameter estimates from the CLPM, RI-CLPM, and LCM under different data-generating processes.


